name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.10

    - name: Set environment variables
      env:
        DATABASE_URL: postgresql://postgres:!C0mplex@localhost/test
      run: |
        echo "DATABASE_URL=$DATABASE_URL" >> $GITHUB_ENV

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: activate venv
      run: venv\Scripts\activate

    - name: Run unittests
      run: python -m unittest discover -s src/tests -t src
