name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      run: |
        choco install python --version=3.10.10 -y -verbose
        python --version

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: activate venv
      run: venv\Scripts\activate

    - name: Run unittests
      run: python -m unittest discover -s src/tests -t src
